version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: vinyl_postgres_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root 
      - POSTGRES_DB=vinyl_collection
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: